resource "local_file" "ansible_inventory" {
  content = <<-EOT
# Ansible Inventory - Auto-generated by Terraform
# Last updated: ${timestamp()}

# ===== Host Groups =====
[master]
${aws_instance.Master_server.private_ip}

[worker]
%{for ip in aws_instance.Worker_server[*].private_ip~}
${ip}
%{endfor~}

[monitoring]
${aws_instance.monitoring_server.public_ip}

# ===== Group Hierarchy =====
[k3s_cluster:children]
master
worker

# ===== Monitoring Targets (Node Exporter 설치 대상) =====
[node_exporter:children]
master
worker

# ===== Global Variables =====
[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=${abspath(path.module)}/../ansible/key/Hello_kt.pem
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# ===== Monitoring Server Variables =====
[monitoring:vars]
# 모니터링 서버는 public IP로 직접 접속
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# ===== Private Nodes (ProxyJump via Bastion) =====
[k3s_cluster:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q ubuntu@${aws_instance.monitoring_server.public_ip} -i ${abspath(path.module)}/../ansible/key/Hello_kt.pem"'

# ===== Prometheus Target Discovery =====
[monitoring:vars]
prometheus_scrape_targets=${jsonencode({
  master = [aws_instance.Master_server.private_ip],
  workers = aws_instance.Worker_server[*].private_ip
})}
EOT

  filename = "${path.module}/../ansible/inventory/aws.ini"
  
  depends_on = [
    aws_instance.Master_server,
    aws_instance.Worker_server,
    aws_instance.monitoring_server,
    local_file.ssh_key
  ]
}