output "monitoring_public_ip" {
  value       = aws_instance.monitoring_server.public_ip
  description = "Public IP of monitoring/jump server"
}

output "master_private_ip" {
  value       = aws_instance.Master_server.private_ip
  description = "Master private IP"
}

output "worker_1_private_ip" {
  value       = aws_instance.Worker_server[0].private_ip
  description = "Worker 1 private IP"
}

output "worker_2_private_ip" {
  value       = aws_instance.Worker_server[1].private_ip
  description = "Worker 2 private IP"
}

output "inventory_path" {
  value       = "${path.module}/../ansible/inventory/aws.ini"
  description = "Ansible inventory file path generated by Terraform"
}

output "ssh_key_path" {
  value       = "${path.module}/../ansible/key/Hello_kt.pem"
  description = "Path to generated SSH private key"
}